<!DOCTYPE html>
<html>
<head>
    <title>BUYSELL</title>
</head>
<body>
<h1 align="center">BUYSELL!</h1> <hr>
<h4 align="center">All products of the world!</h4>
<h3>Create a product</h3>
<form action="/product/create" method="post">
    Product: <input type="text" name="title"/> <br><br>
    Description: <input type="text" name="description"/> <br><br>
    Price: <input type="number" name="price"/> <br><br>
    City: <input type="text" name="title"/> <br><br>
    Name: <input type="text" name="author"/> <br><br>
    <input type="submit" value="Create"/>
</form>

<hr>

</body>
</html>